spring.application.name=database

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/itsi_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=itsi_user
spring.datasource.password=itsi_password
spring.sql.init.mode=always

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=5050

# Initialize database with schema.sql
spring.sql.init.platform=postgresql

# Swagger UI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
